### ISSUE TITLE
Suggestions d'ajout ATM 7

### ISSUE THREAD

**Issue by Annelauremam** [Mineaurion/Support#6]
Aprés test concluant en solo j'aimerai que l'on ajoute sur le serveur ATM pour faciliter l'obtention de cette item qui demande du farm dans l'other donc kill de mob + monde très laggy.
 
Mob en question:piglich
Drop:piglich_heart
A ajouté dans kubjs=>data=>hostilenetworks=>data_models
Piglich.json
`{
	"type": "allthemodium:piglich",
	"name": "entity.allthemodium.piglish",
	"name_color": "0xE8E8E8",
	"gui_scale": 1,
	"gui_x_offset": 0,
	"gui_y_offset": 0,
	"gui_z_offset": 0,
	"sim_cost": 128,
	"input": {
		"item": "hostilenetworks:empty_prediction"
	},
	"base_drop": {
		"item": "hostilenetworks:overworld_prediction"
	},
	"trivia": "",
	"fabricator_drops": [
		{
			"item": "allthemodium:piglich_heart",
			"count": 1
		},
		{
			"item": "immersiveengineering:shader_bag_epic",
			"count": 1
		}
	]
}`

**Comment by Gaetann18** [comment]
Si tout est okj de ton côté, vendu. Par contre ca à l'air pas chère pour un mob rare

**Comment by Annelauremam** [comment]
Mis en place le 27/08/2022
